version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust
    volumes:
      - ..:/gsd:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      RUST_LOG: info,gsd=debug
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password1
      DB_NAME: gsd
      DB_SCHEMA: public
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: gsd

volumes:
  postgres-data:
